# Generated by Django 5.0.1 on 2024-01-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True)),
                ('brands', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, upload_to='product_images/')),
                ('sizes', models.CharField(help_text='Comma-separated list of available sizes', max_length=50)),
                ('quantity_available', models.PositiveIntegerField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='brand.category')),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('order', 'category'), name='unique_order_per_each_category'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('id', 'slug')},
        ),
    ]
