# Generated by Django 5.0.1 on 2024-01-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma-separated list of available sizes', max_length=50),
        ),
    ]
