# Generated by Django 5.0.1 on 2024-01-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_meinmenuitems_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeinMenuItems',
            new_name='MainMenuItems',
        ),
    ]
