# Generated by Django 5.0.1 on 2024-01-19 15:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_meinmenuitems_mainmenuitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField()),
                ('reservation', ckeditor.fields.RichTextField()),
                ('opening_hours', ckeditor.fields.RichTextField()),
                ('twitter_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('instagram_lin', models.URLField(blank=True)),
                ('linkedin_text', ckeditor.fields.RichTextField()),
                ('credits_text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
