# Generated by Django 5.0.1 on 2024-01-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='instagram_lin',
            new_name='instagram_link',
        ),
    ]
